CREATE TABLE crc01_nutrimento (id_nutrimento INT PRIMARY KEY, tx_nombre VARCHAR(150) NOT NULL, tx_descripcion TEXT, st_activo BOOLEAN DEFAULT TRUE);
CREATE TABLE crc02_tipo_etiqueta (id_tipo_etiqueta INT PRIMARY KEY, tx_nombre VARCHAR(100) NOT NULL, tx_descripcion TEXT, st_activo BOOLEAN DEFAULT TRUE);
CREATE TABLE crc03_tipo_cantidad_ingrediente (id_tipo_cantidad_ingrediente INT PRIMARY KEY, tx_nombre VARCHAR(100) NOT NULL, tx_descripcion TEXT, st_activo BOOLEAN DEFAULT TRUE);
CREATE TABLE crc04_tipo_cantidad_nutrimento (id_tipo_cantidad_nutrimento INT PRIMARY KEY, tx_nombre VARCHAR(100) NOT NULL, tx_descripcion TEXT, db_factor DOUBLE PRECISION, st_activo BOOLEAN DEFAULT TRUE);

CREATE TABLE trc01_receta (id_receta SERIAL PRIMARY KEY, fk_id_receta_padre INT, tx_nombre VARCHAR(100) NOT NULL, tx_descripcion TEXT, tm_duracion TIME, fh_registro TIMESTAMP NOT NULL, fh_actualizacion TIMESTAMP NOT NULL, nu_veces_realizada INT NOT NULL, fh_ultima_realizacion TIMESTAMP, CONSTRAINT fk_receta_receta_padre FOREIGN KEY (fk_id_receta_padre) REFERENCES trc01_receta(id_receta));
CREATE TABLE trc02_ingrediente (id_ingrediente SERIAL PRIMARY KEY, tx_nombre VARCHAR(100) NOT NULL);
CREATE TABLE trc03_etiqueta (id_etiqueta SERIAL PRIMARY KEY, fk_id_tipo INT NOT NULL, tx_nombre VARCHAR(100) NOT NULL, tx_color VARCHAR(8), CONSTRAINT fk_etiqueta_tipo FOREIGN KEY (fk_id_tipo) REFERENCES crc02_tipo_etiqueta(id_tipo_etiqueta));
CREATE TABLE trc04_instruccion (id_instruccion SERIAL PRIMARY KEY, fk_id_receta INT NOT NULL, tx_instruccion TEXT NOT NULL, CONSTRAINT fk_instruccion_receta FOREIGN KEY (fk_id_receta) REFERENCES trc01_receta(id_receta));
CREATE TABLE trc05_receta_ingrediente (fk_id_receta INT NOT NULL, fk_id_ingrediente INT NOT NULL, fk_id_tipo_cantidad INT NOT NULL, db_cantidad DOUBLE PRECISION, tx_cantidad VARCHAR(100), PRIMARY KEY (fk_id_receta, fk_id_ingrediente), CONSTRAINT fk_recing_rec FOREIGN KEY (fk_id_receta) REFERENCES trc01_receta(id_receta), CONSTRAINT fk_recing_ing FOREIGN KEY (fk_id_ingrediente) REFERENCES trc02_ingrediente(id_ingrediente), CONSTRAINT fk_recing_tipo FOREIGN KEY (fk_id_tipo_cantidad) REFERENCES crc03_tipo_cantidad_ingrediente(id_tipo_cantidad_ingrediente));
CREATE TABLE trc06_receta_etiqueta (fk_id_receta INT NOT NULL, fk_id_etiqueta INT NOT NULL, PRIMARY KEY (fk_id_receta, fk_id_etiqueta), CONSTRAINT fk_recetaetq_receta FOREIGN KEY (fk_id_receta) REFERENCES trc01_receta(id_receta), CONSTRAINT fk_recetaetq_etiqueta FOREIGN KEY (fk_id_etiqueta) REFERENCES trc03_etiqueta(id_etiqueta));
CREATE TABLE trc07_ingrediente_etiqueta (fk_id_ingrediente INT NOT NULL, fk_id_etiqueta INT NOT NULL, PRIMARY KEY (fk_id_ingrediente, fk_id_etiqueta), CONSTRAINT fk_ingetq_ing FOREIGN KEY (fk_id_ingrediente) REFERENCES trc02_ingrediente(id_ingrediente), CONSTRAINT fk_ingetq_etq FOREIGN KEY (fk_id_etiqueta) REFERENCES trc03_etiqueta(id_etiqueta));
CREATE TABLE trc08_nutrimento_ingrediente (fk_id_nutrimento INT NOT NULL, fk_id_ingrediente INT NOT NULL, db_porcentaje DOUBLE PRECISION, CONSTRAINT pk_trc08_nutrimento_ingrediente PRIMARY KEY (fk_id_nutrimento, fk_id_ingrediente), CONSTRAINT fk_trc08_nutrimento FOREIGN KEY (fk_id_nutrimento) REFERENCES crc01_nutrimento(id_nutrimento), CONSTRAINT fk_trc08_ingrediente FOREIGN KEY (fk_id_ingrediente) REFERENCES trc02_ingrediente(id_ingrediente));
